<?php $this->headTitle()->prepend(' | Catégories') ?>
<?php $this->headMeta()->appendName('description', "Retrouver une multitude de dessins fan art"); ?>
<?= $this->breadcrumb( $this->breadcrumb ) ?>
<div class="row">
  <div class="span2">
    &nbsp;
  </div>
  <div class="span6">
    <h1>Catégories</h1>

    <?php foreach ($this->categories as $category): ?>
      <?php if (count($category->subcategories)): ?>
        <h3><?= $category->name ?></h3>
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th style="width:300px;">Nom</th>
              <th>Nombre de dessins</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($category->subcategories as $subcategory): ?>
            <tr>
              <td><a href="<?= $subcategory->drawings_count ? $this->subcategoryUrl($subcategory) : '#' ?>"><?= $subcategory->name ?></a></td>
              <td><?= $subcategory->drawings_count ?></td>
            </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      <?php endif; ?>
    <?php endforeach; ?>

  </div>
  <div class="span2">
    &nbsp;
  </div>
</div>