<?php $this->headTitle()->prepend(' | '.$this->escape($this->subcategory->name)) ?>
<?php $this->headMeta()->appendName('description', "Retrouver une multitude de dessins fan art de " . $this->escape($this->subcategory->name)); ?>
<?= $this->breadcrumb( $this->breadcrumb ) ?>
<ul class="thumbnails">
  <?php foreach($this->paginator as $drawing): ?>
  <li class="thumbnail">
    <a href="<?= $this->drawingUrl($drawing->drawing_id, $drawing->drawing_name) ?>"><img src="<?= $this->fileUrl($drawing, 210, 280) ?>" width="210" height="280" alt="<?= $drawing->drawing_name ?>"></a>
  </li>
  <?php endforeach;?>
</ul>
<?= $this->paginationControl($this->paginator, null, '_pagination.phtml') ?>