<?php $this->headTitle()->prepend(' | Conditions générales d\'utilisation') ?>
<?= $this->breadcrumb( $this->breadcrumb ) ?>
<div class="row">
  <div class="span2">
    &nbsp;
  </div>
  <div class="span12">
    <h1>Conditions générales d'utilisation</h1>

    <p>Les présentes Conditions Générales d'Utilisation décrivent les termes et conditions dans lesquels www.fan-art.fr fournit un service de partage et d'hébergement de dessin fan art (ci-après "fan art") à l'utilisateur (ci-après "l'utilisateur").<p>
    <p>L’accès à ce Service est subordonné au respect des présentes Conditions Générales d’Utilisation. Tout internaute souhaitant y accéder doit avoir pris connaissance préalablement de ces Conditions Générales d’Utilisation et s'engage à les respecter sans réserve.</p>
    <p>Les fan art ne sont pas de la responsabilité du propriétaire du site.</p>
    <p>www.fanart.fr se réserve le droit de supprimer toutes images à caractère pornographique.<br /> L'utilisateur certifie avoir tous les droits sur les images qu'il ajoute.</p>

    <p>Créateur, Auteur, Utilisateur :<br />
    Dans le cadre du service mis à disposition par www.fan-art.fr, désigne toute personne qui utilise l'outil pour créer et éditer ses pages de dessins.</p>

    <p>Commentaires :<br />
    Les commentaires ont pour vocation de rendre une page interactif. Ainsi, chaque visiteur/utilisateur peut commenter un fan art qu’il viSite.</p>

    <p>Fan art :<br />
    Le fanart ou fan art désigne en anglais toute œuvre réalisée par un fan et s’inspirant ou reproduisant un ou plusieurs personnages, une scène ou l’univers d’une œuvre existante, qu’elle soit littéraire, picturale ou audiovisuelle. Ce terme ne se limite pas qu'aux dessins comme beaucoup peuvent le croire mais bien à tout types et tout supports.</p>

  </div>
  <div class="span2">
    &nbsp;
  </div>
</div>