<div class="row">
  <div class="span3">
    &nbsp;
  </div>
  <div class="span10">
    <h1>An error occurred</h1>
    <pre><?php echo $this->message ?></pre>

    <?php if (isset($this->exception)): ?>

    <h3>Exception message</h3>
    <pre><?php echo $this->exception->getMessage() ?></pre>

    <h3>Stack trace</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?></pre>

    <h3>Request parameters</h3>
    <?php Zend_Debug::dump($this->request->getParams()) ?>

    <?php endif ?>
  </div>
  <div class="span3">
    &nbsp;
  </div>
</div>