<?= $this->breadcrumb( $this->breadcrumb ) ?>
<div class="row">
  <div class="span2">
    &nbsp;
  </div>
  <div class="span12">
    <h1>Sous-catégorie</h1>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>id</th>
          <th>Nom</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->paginator as $category): ?>
        <tr>
          <td><?= $category->id ?></td>
          <td><?= $category->name ?></td>
        </tr>
        <?php endforeach;?>
      </tbody>
    </table>
    <?= $this->paginationControl($this->paginator, null, '_pagination.phtml') ?>
  </div>
  <div class="span2">
    &nbsp;
  </div>
</div>