<?php $this->headTitle()->prepend(' | Utilisateurs') ?>
<?= $this->breadcrumb( $this->breadcrumb ) ?>
<div class="row">
  <div class="span2">
    &nbsp;
  </div>
  <div class="span6">
    <h1>Utilisateurs</h1>
    <p>Découvrez les dessins des utilisateurs de la plateforme.</p>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th style="width:300px;">Pseudo</th>
          <th>Nombre de dessin</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->paginator as $user): ?>
        <tr>
          <?php $count = $user->findDrawingsCount() ?>
          <td><a href="<?= $count ? $this->userUrl($user) : '#' ?>"><?= $user->login ?></a></td>
          <td><?= $count ?></td>
        </tr>
        <?php endforeach;?>
      </tbody>
    </table>
    <?= $this->paginationControl($this->paginator, null, '_pagination.phtml') ?>
  </div>
  <div class="span2">
    &nbsp;
  </div>
</div>