<table style="font-family:Verdana,sans-serif; font-size:11px; color:#374953; width: 100%;">
  <tr>
    <td align="left">
      <a href="<?= $this->serverUrl($this->baseUrl('/')) ?>" title="fanart" style="font-size:14px;font-weight:bold; text-decoration:none;" ><strong style="color:#6FC507;">FanArt</strong> <strong style="color:#000000;">France</strong></a>
    </td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td align="left">Message formulaire de contact,</td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td align="left" style="background-color:#6FC507; color:#FFF; font-size: 12px; font-weight:bold; padding: 0.5em 1em;">De : <?= $this->post['email'] ?></td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td align="left">
      Objet : <?= $this->post['object'] ?>
    </td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td>
      <?= nl2br($this->post['message']) ?>
    </td>
  </tr>
  <tr><td>&nbsp;</td></tr>
  <tr>
    <td align="center" style="font-size:10px; border-top: 1px solid #D9DADE;">
      Ceci est un message automatique, merci de ne pas y r&eacute;pondre.
    </td>
  </tr>
</table>
